language: csharp
solution: ./Datamining.sln
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./Datamining.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Datamining_Test/bin/Release/Datamining_Test.dll